language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install codecov
script: python3 tests.py # run tests
after_success:
  - codecov # submit coverage
